name: oxide_generator
description: "Oxide dev-only code generator (ChangeNotifier + useOxide-style access)."
version: 0.1.0
homepage: https://github.com/Oxide-Stack/Oxide
repository: https://github.com/Oxide-Stack/Oxide
documentation: https://github.com/Oxide-Stack/Oxide
issue_tracker: https://github.com/Oxide-Stack/Oxide/issues

environment:
  sdk: ^3.10.4

dependencies:
  analyzer: ^7.7.1
  build: ^2.5.4
  dart_style: ^3.1.1
  oxide_annotations: ^0.1.0
  source_gen: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
